apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: metermonitor-sources
    - name: namespace
  sourceRef:
    kind: GitRepository
    name: metermonitor
  path: ./flux/headlamp/base
  prune: true
  # wait: true  # rely on healthChecks
  timeout: 10m
