apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metermonitor-kafka
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: metermonitor-namespace
  sourceRef:
    kind: GitRepository
    name: metermonitor
  path: ./flux/kafka/base
  prune: true
  wait: true
  timeout: 10m
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: kafka
      namespace: openmeter
