apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metermonitor-namespace
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: metermonitor
  path: ./flux/infrastructure/namespace/dev
  prune: false
  wait: true
  timeout: 5m
