apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      version: "0.38.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
