apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: openmeter
  namespace: flux-system
spec:
  interval: 6h
  url: oci://ghcr.io/openmeterio/helm-charts/openmeter
  ref:
    semver: "*"
