apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmeter
  namespace: openmeter
spec:
  interval: 30m
  releaseName: openmeter
  chart:
    spec:
      chart: openmeter
      version: ">=1.0.0-beta.0"
      sourceRef:
        kind: HelmRepository
        name: openmeter
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    # Disable bundled PostgreSQL and Redis - use external from flicknote-dev
    postgresql:
      enabled: false
    redis:
      enabled: false

    # Keep bundled Kafka and ClickHouse with stable image tags
    kafka:
      enabled: true
      image:
        tag: "3.8"
    clickhouse:
      enabled: true

    # Svix webhook service - configured via valuesFrom in deployment overlay
    svix:
      enabled: true
      # redis.dsn and postgres.dsn set via valuesFrom

    # OpenMeter config - postgres/redis configured via valuesFrom in deployment overlay
    config:
      # postgres.url set via valuesFrom
      postgres:
        autoMigrate: ent

      # sink.dedupe configured via valuesFrom

      # Meters configuration (from docker-compose)
      meters:
        - slug: api_requests_total
          description: Total API Requests
          eventType: request
          aggregation: COUNT
          groupBy:
            method: $.method
            route: $.route
        - slug: api_requests_duration
          description: API Request Duration
          eventType: request
          aggregation: SUM
          valueProperty: $.duration_ms
          groupBy:
            method: $.method
            route: $.route
        - slug: transcription_minutes
          description: Transcription Minutes by Model
          eventType: transcription
          aggregation: SUM
          valueProperty: $.duration_minutes
          groupBy:
            model: $.model

      # Portal configuration
      portal:
        enabled: true
