apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmeter
  namespace: flicknote-monitor
spec:
  interval: 30m
  releaseName: openmeter
  chart:
    spec:
      chart: openmeter
      version: ">=1.0.0-beta.0"
      sourceRef:
        kind: HelmRepository
        name: openmeter
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  # Use secrets from flicknote-dev namespace for postgres/redis URLs
  valuesFrom:
    - kind: Secret
      name: cnpg-openmeter-password
      valuesKey: postgres-url
      targetPath: config.postgres.url
  values:
    # Disable bundled dependencies - use external from flicknote-dev
    postgresql:
      enabled: false
    redis:
      enabled: false
    kafka:
      enabled: false

    # Keep bundled ClickHouse (Altinity operator)
    clickhouse:
      enabled: true

    # Disable billing and notification services (not needed per docker-compose)
    billingWorker:
      replicaCount: 0
    notificationService:
      replicaCount: 0

    # Disable billing cron jobs (not in docker-compose)
    jobs:
      subscriptionSync:
        enabled: false
      billingCollectInvoices:
        enabled: false
      billingAdvanceInvoices:
        enabled: false

    # Svix webhook service (disabled)
    svix:
      enabled: false

    # OpenMeter configuration
    config:
      # Kafka-compatible broker - using Redpanda from flicknote-infra namespace
      ingest:
        kafka:
          broker: redpanda.flicknote-infra.svc:9092
          brokerAddressFamily: v4
          socketKeepAliveEnable: true
          topicMetadataRefreshInterval: 10s

      # Aggregation - ClickHouse (bundled)
      aggregation:
        clickhouse:
          address: openmeter-clickhouse:9000

      sink:
        minCommitCount: 1
        namespaceRefetch: 1s
        namespaceRefetchTimeout: 1s
        kafka:
          brokers: redpanda.flicknote-infra.svc:9092
          brokerAddressFamily: v4
          socketKeepAliveEnable: true
          topicMetadataRefreshInterval: 10s
        dedupe:
          enabled: true
          driver: redis
          config:
            address: redis.flicknote-infra.svc:6379
            database: 1
            expiration: 768h  # 32 days

      # postgres.url set via valuesFrom
      postgres:
        autoMigrate: ent

      # Meters configuration (from docker-compose)
      meters:
        - slug: api_requests_total
          description: Total API Requests
          eventType: request
          aggregation: COUNT
          groupBy:
            method: $.method
            route: $.route
        - slug: api_requests_duration
          description: API Request Duration
          eventType: request
          aggregation: SUM
          valueProperty: $.duration_ms
          groupBy:
            method: $.method
            route: $.route
        - slug: transcription_minutes
          description: Transcription Minutes by Model
          eventType: transcription
          aggregation: SUM
          valueProperty: $.duration_minutes
          groupBy:
            model: $.model

      # Portal disabled
      portal:
        enabled: false
